#!/bin/zsh zsh

_to() {
  local cur prev words cword
  _get_comp_words_by_ref cur prev words cword

  if [[ ${cword} -eq 1 ]]; then
    COMPREPLY=($(compgen -W "$(find "$ROOT_CODE_DIR" -maxdepth 1 -type d -printf '%f\n')" -- "$cur"))
  else
    COMPREPLY=($(compgen -W "-p" -- "$ROOT_CODE_DIR"))
  fi
}

complete -F _to to
