#!/bin/zsh zsh

PROJECT_DIRECTORY="${ROOT_CODE_DIR}/giftogram"

function gg_feature() {
 project_names=()

 # Populate the array using a while loop
 echo "directories in $PROJECT_DIRECTORY"
 first_line=true
 while IFS= read -r line; do
   if [ "$first_line" = true ]; then
     first_line=false
     continue
   fi

   project_names+=("$line")
 done < <(find "$PROJECT_DIRECTORY" -maxdepth 1 -type d -not -path "." -not -name ".*" -exec basename {} \; | sort)

  # CREATE A FEATURE BRANCH
  # ask user what project they'll be working (required)
  for i in $(seq 0 $((${#project_names[@]}))); do
      if [ "$i" -eq 0 ]; then
        continue
      fi

      echo "$i: ${project_names[$i]}"
  done
  echo "Select a project to work on (1-${#project_names[@]}): "
  read -r project_index

  selected_project=${project_names[$project_index]}
  to "giftogram/$selected_project"

  # Projects Must start at master
  # if we are not at master, ask to checkout master
  # if response is no exit project
  # if response is yes
  # check if we have a clean working branch
  # if not exit
  # if we are clean, checkout master and pull

  # ask the user for the feature name
  # create a branch with the root project branch name
  # <git_name>/feature/<feature_name>/main

  # ask the user for the first task name then create task branch
  # <git_name>/feature/<feature_name>/<task_name>

  # CREATE A TASK BRANCH
  # ask the user for the task name
  # create a branch based off the feature branch
  # <git_name>/feature/<feature_name>/<task_name>
}

