#!/bin/zsh zsh

function nvpm() {
  if [[ ! -f "./package.json" ]]; then
    echo "Package.json not found."
    return
  fi

  command="${*}"
  if [[ "$command" == "" ]]; then
    command="install"
  fi

  # If there is an .nvmrc file, use nvm to set the node version
  if [[ -f "./.nvmrc" ]]; then
    nvm use && npm "$command"
    return
  fi

  npm "${*}"
}
