#!/bin/zsh zsh

function nvpm() {
  if [[ ! -f "./package.json" ]]; then
    echo "Package.json not found."
    return
  fi

  if [[ -f "./.nvmrc" ]]; then
    command="$*"
    if [[ "$command" == "" ]]; then
      command="install"
    fi

    nvm use && npm "$command"
    return
  fi

  npm "$*"
}
