#!/bin/zsh zsh

function startapp() {
  local dev_apps
  dev_apps=("frontend" "react" "admin")

  if [[ -z "$1" ]]; then
    echo "Please provide a name for the app (${dev_apps[*]})"
    return
  fi

  local app
  app="$1"

  if [[ "$1" == "c9" ]]; then
    if [[ "$2" == "" ]]; then
      echo "You must provide a name for the app on you c9."
      return
    fi

    to c9 "$1" "nvpm run dev"
    return
  fi

  if [[ " ${dev_apps[*]} " =~ $app ]]; then
    to "$1" && nvpm run dev
  fi

  echo "App $app not found."
}
