#!/bin/zsh zsh

function startapp() {
  if [[ -z "$1" ]]; then
    echo "Please provide a name for the app (react, admin)"
    return
  fi

  local app
  app="$1"

  local dev_apps
  dev_apps=("frontend" "react" "admin")

  if [[ -v dev_apps["$app"] ]]; then
    to "$app"
    nvpm run dev
  fi

  echo "App $app not found."
}
