#!/bin/zsh zsh

function to () {
  local ON_LOCAL
  ON_LOCAL=false
  local ON_REMOTE
  ON_REMOTE=false

  if [[ "$IAM" == "$LOCAL_MACHINE_NAME" ]]; then
    ON_LOCAL=true
  elif [[ "$IAM" == "$REMOTE_MACHINE_NAME" ]]; then
    ON_REMOTE=true
  fi

  if [[ -z "$ROOT_CODE_DIR" ]]; then
    echo "ROOT_CODE_DIR is not set. Please set it in '~/.oh-my-zsh/env.zsh'."
    return
  fi

  if [[ "$1" == "help" ]]; then
      cat <<EOF
    Usage: to [OPTIONS] <project_name>

    This script navigates to project directories based on predefined rules and can optionally open the directory in PHPStorm for specific users.

    Arguments:
      project_name       Name of the project to navigate to. Matches specific keywords to determine the correct directory.

    Options:
      -p                 Open the directory in PHPStorm (only works in the "todd" user environment).
      --                 Indicates the end of options.

    Environment Variables:
      ROOT_CODE_DIR      This variable must be set. Represents the root directory containing the project folders.
                         Ensure it is set in '~/.oh-my-zsh/loader.sh'.
      IAM                Identifies the current user.
                         Options:
                           - "todd": Allows opening projects in PHPStorm.
                           - "ubuntu": Uses specific rules to map project names to directories.

    Examples:
      to ordersite       Navigate to the "ordersite" project directory.
      to -p admin        Navigate to the "admin" project directory and open it in PHPStorm (only if IAM='todd').

    Autocompletion:
      - This script supports tab autocompletion for project names and the `-p` option.
      - Autocompletion derives directories from the contents of the ROOT_CODE_DIR variable.

    Notes:
      - If the project directory does not exist, an error will be displayed.
      - If the ROOT_CODE_DIR variable is not set, the script will abort with a message.

EOF
    return
  fi

  local OPEN_PSTORM
  OPEN_PSTORM=false
  local PROJECT
  PROJECT="$1"

  if [[ "$ON_LOCAL" == true ]]; then
    if [[ "$1" == "ordersite" ]]; then
        PROJECT="ordersite/dev/api"
    fi

    if [[ "$1" == "admin" ]]; then
        PROJECT="admin/site"
    fi
  elif [[ "$ON_REMOTE" == true ]]; then
    if [[ "$1" == "giftogram-order-site" || "$1" == "ordersite"  || "$1" == "order" ]]; then
        PROJECT="giftogram-order-site/dev/api"
    fi
    if [[ "$1" == "api" ]]; then
        PROJECT="gg-api"
    fi

    if [[ "$1" == "giftogram-admin" || "$1" == "admin" ]]; then
        PROJECT="giftogram-admin/site"
    fi
  fi

  local CODE_DIR
  CODE_DIR="$ROOT_CODE_DIR/$PROJECT"

  while test $# != 0
  do
      case "$1" in
      -p) OPEN_PSTORM=true ;;
      --) shift; break;;
      esac
      shift
  done

  if [ ! -d "$CODE_DIR" ]; then
      echo "\"$CODE_DIR\" not found."
      return
  fi

  echo "Moving to: $CODE_DIR"
  cd "$CODE_DIR" || exit 1;

  if [[ "$ON_LOCAL" == false  && "$OPEN_PSTORM" == true ]]; then
    echo "Can not open directory in PHPStorm in this environment."
  fi

  if [[ "$ON_LOCAL" == true && "$OPEN_PSTORM" == true ]]; then
    phpstorm .
  fi
}

