#!/bin/zsh

alias gitcm="git checkout master && git pull"
alias gitreset="git reset --hard HEAD && git clean -f -d"
alias gitp="git pull"
alias gitc="git checkout"
alias gitcmu="git checkout master && updategg"
alias gitignite="gitreset && gitcmu"
